version: 0.2

phases:
   pre_build:
    commands:
      - npm install
      
   build:
    commands:  
      - npm i --save-dev @react-native-community/cli
     # - npm react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug
      
artifacts:
  files:
      - /app/build/outputs/apk/release/*.apk
