version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
   pre_build:
    commands:
      # Build the react app to give an optimized production build
      - npm run build
   build:
    commands:  
      - npm i @react-native-community/cli-platform-android
     # - npm react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug
      - react-native run-android
artifacts:
  files:
    - '**/*.apk'
