export const FONT_FAMILY = {
    "BentonSansBlack":"BentonSans Black",
    "BentonSansBold":"BentonSans Bold",
    "BentonSansBook":"BentonSans Book",
    "BentonSansMedium":"BentonSans Medium",
    "BentonSansRegular":"BentonSans Regular",
    "MontserratBlack":"Montserrat-Black",
    "MontserratBlackItalic":"Montserrat-BlackItalic",
    "MontserratBlackBold":"Montserrat-BlackBold",
    "MontserratBlackBoldItalic":"Montserrat-BlackBoldItalic",
    "MontserratExtraLight":"Montserrat-ExtraLight",
    "MontserratExtraLightItalic":"Montserrat-ExtraLightItalic",
    "MontserratItalic":"Montserrat-Italic",
    "MontserratLightItalic":"Montserrat-LightItalic",
    "MontserratMedium":"Montserrat-Medium",
    "MontserratRegular":"Montserrat-Regular",
    "MontserratSemiBold":"Montserrat-SemiBold",
    "MontserratSemiBoldItalic":"Montserrat-SemiBoldItalic",
    "MontserratThin":"Montserrat-Thin",
    "MontserratThinItalic":"Montserrat-ThinItalic",
};
